# Generated by Django 4.2 on 2025-03-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_discount_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed_exploitant', 'تم التأكيد من المشغل'), ('pending_pdg', 'في انتظار تأكيد المدير العام'), ('unpaid', 'غير مدفوعة'), ('paid', 'مدفوعة'), ('confirmed', 'مؤكدة')], default='pending', max_length=20),
        ),
    ]
